server.port : 8080
spring:
  application.name: jpa-practice

  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/myOrganization
      username: root
      password: Test@456
      driver-class-name: com.mysql.cj.jdbc.Driver
    postgresql:
      jdbc-url: jdbc:postgresql://localhost:5432/mydb
      username: postgres
      password: Test@456
      driver-class-name: org.postgresql.Driver

  jpa:
    mysql:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate.ddl-auto-update: none
      show-sql : true
    postgresSql:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate.ddl-auto-update: none


logging:
  level:
    org.hibernate.sql : Trace
    org.hibernate.orm.jdbc.bind : Trace











