server.port : 8080
spring:
  application.name: jpa-practice

  datasource:
      url: jdbc:mysql://localhost:3306/myOrganization
      username: root
      password: Test@456
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
     database-platform: org.hibernate.dialect.MySQL8Dialect
     hibernate.ddl-auto-update: none



logging:
  level:
    org.hibernate.sql : Trace
    org.hibernate.orm.jdbc.bind : Trace











